# Generated by Claude Code
ARCH  := x86_64
CC    := gcc
AR    := ar
BUILD := build

CPPFLAGS := -Iinclude -Iarch/$(ARCH) \
			-Isrc/internal
CFLAGS   := -std=c11 -O2 -Wall -Wextra \
            -ffreestanding -nostdinc -fno-builtin \
            -fno-stack-protector -fno-pie \
			-fno-tree-loop-distribute-patterns

SRCS  := $(wildcard src/*/*.c)
OBJS  := $(SRCS:%.c=$(BUILD)/obj/%.o)
LIB   := $(BUILD)/lib/libwdxc.a
CRT1  := $(BUILD)/lib/crt1.o
TESTS := $(patsubst tests/%.c,$(BUILD)/tests/%,$(wildcard tests/*.c))

all: $(LIB) $(CRT1) $(TESTS)

$(BUILD)/obj/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(CRT1): arch/$(ARCH)/crt1.S
	@mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) -c $< -o $@

$(LIB): $(OBJS)
	@mkdir -p $(dir $@)
	rm -f $@
	$(AR) rcs $@ $^

$(BUILD)/tests/%: $(BUILD)/obj/tests/%.o $(LIB) $(CRT1)
	@mkdir -p $(dir $@)
	$(CC) -static -no-pie -nostdlib $(CRT1) $< $(LIB) -o $@

test: $(TESTS)
	@for t in $(TESTS); do echo "== $$t"; $$t || exit 1; done

clean:
	rm -rf $(BUILD)

.PHONY: all test clean
.SECONDARY: